language: python
os: linux
dist: xenial
version: ~> 1.0


install:
  - pip install pylint

before_script:
  - pwd
  - ls -l

python:
  - '2.7'
  - '3.6'
  - '3.7'

jobs:  
  - stage: run_matrix
#   python: ['2.7','3.6','3.7']
#    - '2.7'
#    - '3.6'
#    - '3.7'
    script:
     - ./script1.py
     - ./script2.py
     - ./script3.py

  - stage: run_hello
#   python: ['2.7','3.6','3.7']
#    - '2.7'
#    - '3.6'
#    - '3.7'
    script:
     - ./hello_world.py

#jobs:
#  include:
#    - stage: run_hello
#      python: '3.7'
#      script:
#        - ./hello_world.py


after_script:
  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
