language: python

python: 
 - 2.7
 - 3.6

#install:
#  - bash

before_script:
  - pwd
  - ls -l

script: 
  - ./hello_world.py

#
branches:
        only:
                - master
                - travis
