language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

jobs:
  - allow_failures:
     - linting
script: 
  - jobs:
    - prelim:
       - pwd
       - which pylint
       - ls -l
    - hello:
       - ./hello_world.py
    - linting:
       - pylint ./hello_world.py

#after_script:

#
branches:
        only:
                - master
                - travis
