language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

jobs:
  - allow_failure:
    - pylint

scripts:
  - pwd
  - which pylint
  - ls -l
  - ./hello_world.py
  - pylint ./hello_world.py

#script: 
#  - prelim
#  - hello
#  - linting

#after_script:

#
branches:
        only:
                - master
                - travis
