language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

jobs:
    - prelim:
       - pwd
       - which pylint
       - ls -l
    - hello:
       - ./hello_world.py
    - linting:
       - pylint ./hello_world.py
    - allow_failures:
       - linting
script: 
  - prelim
  - hello:
  - linting:

#after_script:

#
branches:
        only:
                - master
                - travis
