language: python
os: linux
dist: xenial

before_install:
  - pip install pylint


jobs:
  - include:
    - stage: test
      script: 
        - pwd
        - which pylint
        - ls -l
    - stage: run_hello
        - python: 
          - 2.7
          - 3.6
      script: ./hello_world.py
    - stage: linting
        - python: 
          - 2.7
          - 3.6
      script: pylint ./hello_world.py
  - allow_failure:
    - linting

#after_script:

#
branches:
        only:
                - master
                - travis
