language: python
python: 3.6
os: linux
dist: xenial

before_install:
  - pip install pylint



jobs:
  - include:
    - stage: test
      script: 
        - pwd
        - which pylint
        - ls -l
    - stage: run_hello
      script: ./hello_world.py
  - allow_failure:
    - linting

after_script:
  - python:
     - 2.7
     - 3.6
  - stage: linting
    - pylint ./hello_world.py

#
branches:
        only:
                - master
                - travis
