language: python
os: linux
dist: xenial
version: ~> 1.0


install:
  - pip install pylint

before_script:
  - pwd
  - ls -l

# set up job maxtrix
# in Travis settings, set allow concurent jobs >1
stage: run_matrix
python:
  - '2.7'
  - '3.6'
  - '3.7'
script:
  - ./script1.py
  - ./script2.py
  - ./script3.py

# add explictly 3 more jobs
jobs:  
  include:
  - stage: run_hello_2.7
    python: '2.7'
    script:
     - ./hello_world.py
  - stage: run_hello_3.6
    python: '3.6'
    script:
     - ./hello_world.py
  - stage: run_hello_3.7
    python: '3.7'
    script:
     - ./hello_world.py

# after script, lint the python
after_script:
  - name: linting
    python: '3.6'
    pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
