language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

jobs:
  -include:
    - name: prelim
       - pwd
       - which pylint
       - ls -l
    - name: hello
       - ./hello_world.py
    - name: linting
       - pylint ./hello_world.py
    - allow_failures:
       - linting

script: 
  - prelim
  - hello
  - linting

#after_script:

#
branches:
        only:
                - master
                - travis
