language: python

before_install:
  - pip install pylint

python: 
 - 2.7
 - 3.6

jobs:
  - include:
    - stage: test
      script: 
        - pwd
        - which pylint
        - ls -l
    - stage: run_hello
      script: ./hello_world.py
    - stage: linting
      script: pylint ./hello_world.py
  - allow_failure:
    - linting

#after_script:

#
branches:
        only:
                - master
                - travis
