language: python
os: linux
version: ~> 1.0

branches:
  only:
    - master
    - travis

install:
  - pip install pylint

before_script:
  - pwd
  - ls -l

# set up job maxtrix
# in Travis settings, set allow concurent jobs >1
# these jobs run concurrently
stage: "run_matrix"
sudo: enabled
dist: xenial

# job matrix: this is implicit
python:
  - '2.7'
# - '3.3' # failed
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
script:
  - ./script1.py
  - ./script2.py
  - ./script3.py
dist:
  - trusty
  - xenial
  - precise

# add explictly 3 more jobs which run in series
# use 'trusty' dist to be different from above
jobs:  
  include:
  - stage: "run_hello_trusty"
    python: '3.6'
    dist: trusty
    script:
     - ./hello_world.py
  - stage: "run_hello_precise"
    python: '3.6'
    dist: precise
    script:
     - ./hello_world.py
  - stage: "run_hello_xenial"
    python: '3.6'
    dist: xenial
    script:
     - ./hello_world.py

# after script, lint the python
# python version should match script above
after_script:
  - pylint ./hello_world.py


