language: python
os: linux
dist: xenial
version: ~> 1.0

python: "3.6"
#python: 
#  - "3.6"
#  - "2.7"

install:
  - pip install pylint

jobs:
  - include:
    - stage: prelim
      script: 
        - pwd
#       - which pylint
        - ls -l
    - stage: run_hello
      python: 
       - 3.6
       - 2.7
      script: ./hello_world.py

after_script:
  - pylint ./hello_world.py
# - allow_failure: pylint


#
branches:
        only:
                - master
                - travis
