language: python
os: linux
dist: xenial
version: ~> 1.0

#before_install:
#  - pip install pylint

python:
 - "3.6"
 - "3.7"

jobs:
  include:
    - stage: prelim
      script: 
      - pwd
      - ls -l

    - stage: run_matrix
      script:
        - ./script1.py
        - ./script2.py
        - ./script3.py

    - stage: run_hello
      script:
        - ./hello_world.py


#after_script:
#  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
