language: python
os: linux
dist: xenial
version: ~> 1.0

python:
 - '2.7'
 - '3.6'

install:
  - pip install pylint

jobs:
# - include:
#   - stage: prelim
#     script: 
#     - pwd
#     - ls -l
  stage: run_matrix
    python:
#   - '2.7'
    - '3.6'
   script: 
    - ./script1.py
    - ./script2.py 
    - ./script3.py
# - include:
#   - stage: run_hello
#     python: '2.7'
#     script:
#     - ./hello_world.py


after_script:
  - python: '3.7'
    pylint ./hello_world.py
# - allow_failure: pylint


#
branches:
        only:
                - master
                - travis
