language: python
os: linux
dist: xenial
version: ~> 1.0

python: 3.6
#python: 
#  - "2.7"
#  - "3.6"

install:
  stage: pip
  - pip install pylint

#install: skip

jobs:
  - include:
    - stage: prelim
      script: 
        - pwd
#       - which pylint
        - ls -l
    - stage: run_hello
      script: ./hello_world.py

#after_script:
#  - stage: linting
#    script:
#    - pylint ./hello_world.py
#  - allow_failure: linting


#
branches:
        only:
                - master
                - travis
