language: python
os: linux
dist: xenial
version: ~> 1.0


install:
  - pip install pylint

before_script:
  - pwd
  - ls -l

stage: run_matrix
python:
 - '2.7'
 - '3.6'
 - '3.7'
script:
  - stage: fox
    ./script1.py
  - stage: dobalino
    ./script2.py
  - stage: zilch
    ./script3.py


jobs:
  include:
    - stage: run_hello
      python: '3.7'
      script:
        - ./hello_world.py


after_script:
  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
