language: python
os: linux
dist: xenial
version: ~> 1.0


install:
  - pip install pylint

before_script:
  - pwd
  - ls -l

stage: run_maxtrix
python:
  - '2.7'
  - '3.6'
  - '3.7'
script:
  - ./script1.py
  - ./script2.py
  - ./script3.py

jobs:  
  include:
  - stage: run_hello_2.7
    python: '2.7'
    script:
     - ./hello_world.py
  include:
  - stage: run_hello_3.6
    python: '3.6'
    script:
     - ./hello_world.py
  include:
  - stage: run_hello_3.7
    python: '3.7'
    script:
     - ./hello_world.py

#jobs:
#  include:
#    - stage: run_hello
#      python: '3.7'
#      script:
#        - ./hello_world.py


after_script:
  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
