language: python
os: linux
dist: xenial
version: ~> 1.0

install:
  - pip install pylint

jobs:
  include:
    - stage: prelim
      script: 
      - pwd
      - ls -l

#   - stage: run_matrix
#     python:
#     - '2.7'
#     - '3.6'
#     script: 
#     - ./script1.py
#     - ./script2.py 
#     - ./script3.py

    - stage: run_hello
      language: python
      python: 
        - "2.7"
        - "3.6"
      script:
        - ./hello_world.py


#after_script:
#  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
