language: python
os: linux
dist: xenial
version: ~> 1.0


#before_install:
#  -  stage: prelim
#     script: 
#     - pwd
#     - ls -l

install:
  - pip install pylint

before_script:
  name: prelim
  script:
   - pwd
   - ls -l

stage: run_matrix
python:
 - "3.6"
 - "3.7"
script:
  - ./script1.py
  - ./script2.py
  - ./script3.py


jobs:
  include:

    - stage: run_hello
      script:
        - ./hello_world.py


after_script:
  pylint ./hello_world.py


#
branches:
        only:
                - master
                - travis
