language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

scripts:
  - name: prelim
     - pwd
     - which pylint
     - ls -l
  - name: helloworld
     - ./hello_world.py
  - name: linting
     - pylint ./hello_world.py
  - allow_failure:
       - pylint

#script: 
#  - prelim
#  - hello
#  - linting

#after_script:

#
branches:
        only:
                - master
                - travis
