language: python

python: 
 - 2.7
 - 3.6

#install:
#  - bash

#before_script:

services:
  - pylint

script: 
  - pwd
  - ls -l
  - ./hello_world.py

#
branches:
        only:
                - master
                - travis
