language: python
python: 3.6
os: linux
dist: xenial

before_install:
  - stage: "install pylint"
    pip install pylint

jobs:
  - include:
    - stage: test
      script: 
        - pwd
        - which pylint
        - ls -l
    - stage: run_hello
      script: ./hello_world.py

after_script:
  - stage: linting
    script:
    - pylint ./hello_world.py
  - allow_failure:
    - linting

#
branches:
        only:
                - master
                - travis
