language: python
os: linux
dist: xenial
version: ~> 1.0

install:
  - pip install pylint

jobs:
  - include:
    - stage: prelim
      script: 
        - pwd
        - ls -l
    - stage: run_hello
      python: '3.6'
#      - '3.6'
#      - '2.7'
      name: fox
      script: 
         ./script1.py
      name: dobaline
      script:
         ./script2.py 
      name: zilch
      script
         ./script3.py

after_script:
  - pylint ./hello_world.py
# - allow_failure: pylint


#
branches:
        only:
                - master
                - travis
