language: python

python: 
 - 2.7
 - 3.6

install:
  - pip install pylint

script: 
  - pwd
  - ls -l
  - ./hello_world.py

after_script:
  - pylint ./hello_world.py

#
branches:
        only:
                - master
                - travis
